### ISSUE TITLE
Could not resolve "@tact-lang/ton-abi"

### ISSUE THREAD

**Issue by akbariandev** [tact-lang/tact-emulator#11]
I ran the install command mentioned in README and run the script but got below error.

```shell
Could not resolve "@tact-lang/ton-abi"

 node_modules/@tact-lang/emulator/dist/emulator/ContractSystem.js:25:26:
      25 │ const ton_abi_1 = require("@tact-lang/ton-abi");
         ╵                           ~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@tact-lang/ton-abi" as external to exclude it from the bundle,
  which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

8:44:13 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@tact-lang/emulator/dist/emulator/ContractSystem.js:25:26: ERROR: Could not resolve "@tact-lang/ton-abi"
    at failureErrorWithLog (/home/mj/Projects/ton/markyton/ton/test-app/node_modules/esbuild/lib/main.js:1649:15)
    at /home/mj/Projects/ton/markyton/ton/test-app/node_modules/esbuild/lib/main.js:1058:25
    at /home/mj/Projects/ton/markyton/ton/test-app/node_modules/esbuild/lib/main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


```

**Comment by yourdaddy01** [comment]
Could not resolve "@tact-lang/ton-abi"

 node_modules/@tact-lang/emulator/dist/emulator/ContractSystem.js:25:26:
      25 │ const ton_abi_1 = require("@tact-lang/ton-abi");
         ╵                           ~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@tact-lang/ton-abi" as external to exclude it from the bundle,
  which will remove this error. You can also surround this "require" call with a try/catch
  block to handle this failure at run-time instead of bundle-time.

8:44:13 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/@tact-lang/emulator/dist/emulator/ContractSystem.js:25:26: ERROR: Could not resolve "@tact-lang/ton-abi"
    at failureErrorWithLog (/home/mj/Projects/ton/markyton/ton/test-app/node_modules/esbuild/lib/main.js:1649:15)
    at /home/mj/Projects/ton/markyton/ton/test-app/node_modules/esbuild/lib/main.js:1058:25
    at /home/mj/Projects/ton/markyton/ton/test-app/node_modules/esbuild/lib/main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
